name: yx_scope
description: A core package of the compile-safe DI framework with advanced scoping capabilities
version: 1.1.2
repository: https://github.com/yandex/city-services-pub/tree/main/yx_scope/packages/yx_scope
issue_tracker: https://github.com/yandex/city-services-pub/issues
topics:
  - di
  - scope
  - dependency-injection
  - dependency-management

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.1

