name: yx_state_transformers
description: Custom task transformers for yx_state
version: 1.0.0
repository: https://github.com/yandex/city-services-pub/tree/main/yx_state/packages/yx_state_transformers
issue_tracker: https://github.com/yandex/city-services-pub/issues
publish_to: none
topics:
  - yx_state
  - state-management
  - concurrency

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  yx_state: ^1.0.0
  stream_transform: ^2.1.0

dev_dependencies:
