name: yx_state
description: A state management library for Dart/Flutter applications.
version: 1.0.0
repository: https://github.com/yandex/city-services-pub/tree/main/yx_state/packages/yx_state
issue_tracker: https://github.com/yandex/city-services-pub/issues
publish_to: none
topics:
  - yx_state
  - state-management

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.18.2
  mocktail: ^1.0.0

screenshots:
  - description: The yx_state package logo
    path: screenshots/yx_state_logo.webp
